version: '3.4'

services:
  web-server:
    image: nginx
    build: ./web-server/build
    container_name: web-server
    restart: unless-stopped
    networks:
      - container-network
    ports:
    - target: 80
      published: 80
    volumes:
      - ./web-server/nginx.conf:/etc/nginx/nginx.conf
      - ./web-server/upstream:/etc/nginx/upstream
      - ./web-server/servers:/etc/nginx/servers
      - ./web-server/templates:/etc/nginx/templates

networks:
  container-network:
    name: internal-network
    driver: bridge
