version: '3.4'

services:
  web-server:
    image: alpine-nginx
    build: ./web-server/build/
    container_name: web-server
    restart: unless-stopped
    networks:
      - container-network
    ports:
    - 80:80
    - 443:443
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./web-server/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web-server/upstream:/etc/nginx/upstream
      - ./web-server/templates:/etc/nginx/templates
      - servers:/etc/nginx/servers
      - certs:/etc/letsencrypt
      - challenge:/var/www/certbot
    env_file:
      - ./.env

  certbot:
    image: alpine-certbot
    build: ./certbot/build/
    container_name: certbot
    tty: true
    depends_on:
      - web-server
    networks:
      - container-network
    volumes:
      - ./log/certbot:/var/log/certbot
      - servers:/etc/nginx/servers:ro
      - certs:/etc/letsencrypt
      - challenge:/var/www/certbot
    env_file:
      - ./.env

  cron:
    image: alpine-cron
    build: ./cron/build/
    container_name: cron
    depends_on:
      - web-server
      - certbot
    networks:
      - container-network
    volumes:
      - ./log/cron:/var/log/cron
    env_file:
      - ./.env

networks:
  container-network:
    name: internal-network
    driver: bridge

volumes:
  certs:
  challenge:
  servers:
      