version: '3.4'

services:
  web-server:
    image: nginx
    build: ./web-server/build
    container_name: web-server
    restart: unless-stopped
    networks:
      - container-network
    ports:
    - 80:80
    - 443:443
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./web-server/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web-server/upstream:/etc/nginx/upstream
      - ./web-server/servers:/etc/nginx/servers
      - ./web-server/templates:/etc/nginx/templates
    environment:
      - TZ=${TIMEZONE}
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/servers

networks:
  container-network:
    name: internal-network
    driver: bridge
