version: '3.4'

services:
  web-server:
    image: alpine-nginx
    build: ./web-server/build/
    container_name: web-server
    restart: unless-stopped
    networks:
      - container-network
    ports:
    - 80:80
    - 443:443
    volumes:
      - ./log/nginx/:/var/log/nginx/
      - ./web-server/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web-server/upstream:/etc/nginx/upstream:ro
      - ./web-server/templates:/etc/nginx/templates:ro
      - conf:/etc/nginx/conf.d
      - bots:/etc/nginx/bots.d
      - servers:/etc/nginx/servers
      - certs:/etc/letsencrypt
      - challenge:/var/www/certbot
      - web_content:/var/www
    env_file:
      - ./.env

  certbot:
    image: alpine-certbot
    build: ./certbot/build/
    container_name: certbot
    depends_on:
      - web-server
    networks:
      - container-network
    volumes:
      - ./log/certbot:/var/log/certbot
      - servers:/etc/nginx/servers:ro
      - certs:/etc/letsencrypt
      - challenge:/var/www/certbot
    env_file:
      - ./.env

  badbot-blocker:
    image: alpine-badbot-blocker
    build: ./badbot-blocker/build
    container_name: badbot-blocker
    depends_on:
      - web-server
    networks:
      - container-network
    volumes:
      - ./web-server/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./log/badbot-blocker:/var/log/badbot-blocker
      - conf:/etc/nginx/conf.d:rw
      - bots:/etc/nginx/bots.d:rw
      - servers:/etc/nginx/sites-available
      - web_content:/var/www
    env_file:
      - ./.env

  # cron:
  #   image: alpine-cron
  #   build: ./cron/build/
  #   container_name: cron
  #   depends_on:
  #     - web-server
  #     - certbot
  #   networks:
  #     - container-network
  #   volumes:
  #     - ./log/cron:/var/log/cron
  #   env_file:
  #     - ./.env

networks:
  container-network:
    name: internal-network
    driver: bridge

volumes:
  certs:
    name: certs
  challenge:
    name: challenge
  servers:
    name: servers
  conf:
    name: conf
  bots:
    name: bots
  web_content:
    name: web_content