version: '3.4'

services:
  web-server:
    image: nginx
    build: ./web-server/build/
    container_name: web-server
    restart: unless-stopped
    networks:
      - container-network
    ports:
    - 80:80
    - 443:443
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./web-server/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web-server/upstream:/etc/nginx/upstream
      - ./web-server/servers:/etc/nginx/servers
      - ./web-server/templates:/etc/nginx/templates
      - ./certbot/certs:/etc/letsencrypt
      - ./certbot/challenge:/var/www/certbot
    env_file:
      - ./.env

  certbot:
    image: certbot/certbot
    build: ./certbot/build/
    container_name: certbot
    networks:
      - container-network
    volumes:
      - ./certbot/build/parse_servers.sh:/opt/parse_servers.sh
      - ./certbot/certs:/etc/letsencrypt
      - ./certbot/challenge:/var/www/certbot
      - ./certbot/log/certbot:/var/log/
    env_file:
      - ./.env

networks:
  container-network:
    name: internal-network
    driver: bridge
